apiVersion: apps/v1
kind: Deployment
metadata:
  name: dk-ms-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      role: dk-ms-auth
  template:
    metadata:
      labels:
        role: dk-ms-auth
    spec:
      containers:
        - name: auth
          image: magadiflo/auth:latest
          ports:
            - containerPort: 9000
          env:
            - name: LB_USUARIOS_URI
              valueFrom:
                configMapKeyRef:
                  name: dk-ms-usuarios
                  key: lb_usuarios_uri
---
apiVersion: v1
kind: Service
metadata:
  name: dk-ms-auth
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    role: dk-ms-auth
  type: LoadBalancer