apiVersion: apps/v1
kind: Deployment
metadata:
  name: dk-ms-usuarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dk-ms-usuarios
  template:
    metadata:
      labels:
        app: dk-ms-usuarios
    spec:
      containers:
        - image: magadiflo/usuarios:latest
          name: usuarios
          ports:
            - containerPort: 8001
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: dk-ms-usuarios
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: dk-ms-usuarios
                  key: db_host
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: dk-ms-usuarios
                  key: database
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: dk-ms-usuarios
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: dk-ms-usuarios
                  key: password
            - name: CURSOS_URL
              valueFrom:
                configMapKeyRef:
                  name: dk-ms-usuarios
                  key: curso_url