version: "3.9"
services:
  mysql8:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: magadiflo
      MYSQL_DATABASE: bd_dk_ms_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring
  postgres14:
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: magadiflo
      POSTGRES_DB: bd_dk_ms_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring
  dk-ms-usuarios:
    image: usuarios:latest
    ports:
      - "8001:8001"
    env_file:
      - ./dk-ms-usuarios/.env
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always
  dk-ms-cursos:
    image: cursos:latest
    ports:
      - "8002:8002"
    env_file:
      - ./dk-ms-cursos/.env
    networks:
      - spring
    depends_on:
      - postgres14
    restart: always
volumes:
  data-mysql:
  data-postgres:
networks:
    spring:
