apiVersion: apps/v1
kind: Deployment
metadata:
  name: dk-ms-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      role: dk-ms-gateway
  template:
    metadata:
      labels:
        role: dk-ms-gateway
    spec:
      containers:
        - name: gateway
          image: magadiflo/gateway:latest
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: dk-ms-gateway
spec:
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    role: dk-ms-gateway
  type: LoadBalancer